{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-active
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-preview
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
{{- end -}}
